CONTENT_CONTAINER = "#content"
FORGOTTEN_PASSWORD_HEADER = "xpath=//h1[normalize-space()='Forgot Your Password?']"
INSTRUCTION_TEXT = "xpath=//p[contains(text(),'password reset link')]"
FORGOTTEN_FORM = "#form-forgotten"
EMAIL_LEGEND = "xpath=//legend[normalize-space()='Your E-Mail Address']"
EMAIL_INPUT = "#input-email"
EMAIL_ERROR = "#error-email"
BACK_BUTTON = "xpath=//a[contains(@href,'account/login') and normalize-space()='Back']"
CONTINUE_BUTTON = "xpath=//form[@id='form-forgotten']//button[@type='submit' and normalize-space()='Continue']"
