from __future__ import annotations
from typing import Protocol

from tas.domain.models.booking import BookingDraft, BookingRef, Booking

class BookingPort(Protocol):
    def create(self, draft: BookingDraft) -> BookingRef: ...
    def read(self, ref: BookingRef) -> Booking: ...
    def update_put(self, ref: BookingRef, draft: BookingDraft) -> Booking: ...
    def update_patch(self, ref: BookingRef, patch: dict) -> Booking: ...
    def delete(self, ref: BookingRef) -> None: ...
