from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class OpenCartForgotPasswordPageState:
    page_loaded: bool
    instruction_text_visible: bool
    email_field_visible: bool
    continue_button_visible: bool
    back_button_visible: bool


class OpenCartForgotPasswordPagePort(Protocol):

    def open_forgotten_password_page(self) -> None:
        ...
    def read_forgotten_password_page_state(self) -> OpenCartForgotPasswordPageState:
        ...
    def enter_registered_email(self) -> None:
        ...
    def enter_unregistered_email(self) -> None:
        ...
    def enter_invalid_email(self) -> None:
        ...
    def submit_forgotten_password_form(self) -> None:
        ...
    def submit_forgotten_password_form_without_email(self) -> None:
        ...
    def is_forgotten_password_request_accepted(self) -> bool:
        ...
    def is_email_validation_error_displayed(self) -> bool:
        ...
    def click_back_button(self) -> None:
        ...
    def is_login_page_loaded(self) -> bool:
        ...
    def breadcrumb_contains(self, text: str) -> bool:
        ...
    def click_side_menu_login_link(self) -> None:
        ...
    def click_side_menu_register_link(self) -> None:
        ...
    def click_side_menu_forgotten_password_link(self) -> None:
        ...
    def is_register_account_page_loaded(self) -> bool:
        ...
    def set_desktop_viewport(self) -> None:
        ...
    def set_tablet_viewport(self) -> None:
        ...
    def set_mobile_viewport(self) -> None:
        ...
    def is_forgotten_password_form_usable(self) -> bool:
        ...
    def are_forgotten_password_primary_elements_visible(self) -> bool:
        ...
    def forgotten_password_page_uses_https(self) -> bool:
     ...
    def enter_malicious_email_input(self) -> None:
        ...
    def enter_very_long_email(self) -> None:
        ...
    def is_forgotten_password_page_stable(self) -> bool:
        ...
    def is_javascript_alert_displayed(self) -> bool:
        ...
    def submit_form_multiple_times_with_unregistered_email(self) -> None:
        ...
    def refresh_forgotten_password_page(self) -> None:
        ...
    def is_email_field_empty(self) -> bool:
        ...
    def navigate_back_in_browser_to_forgotten_password_page(self) -> None:
        ...
    def open_forgotten_password_page_again(self) -> None:
        ...
