from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class OpenCartRegisterPageState:
    page_loaded: bool
    firstname_field_visible: bool
    lastname_field_visible: bool
    email_field_visible: bool
    password_field_visible: bool
    continue_button_visible: bool
    privacy_policy_link_visible: bool
    login_link_visible: bool


class OpenCartRegisterPagePort(Protocol):

    def open_register_page(self) -> None:
        ...

    def read_register_page_state(self) -> OpenCartRegisterPageState:
        ...

    def fill_registration_form_with_generated_user(self) -> None:
        ...

    def enter_invalid_email(self) -> None:
        ...

    def agree_to_privacy_policy(self) -> None:
        ...

    def submit_registration_form(self) -> None:
        ...

    def submit_registration_form_without_fields(self) -> None:
        ...

    def is_success_message_visible(self, message: str) -> bool:
        ...

    def are_all_mandatory_errors_displayed(self) -> bool:
        ...

    def is_privacy_policy_warning_displayed(self) -> bool:
        ...

    def is_email_validation_error_displayed(self) -> bool:
        ...

    def is_password_field_masked(self) -> bool:
        ...
    
    def refresh_register_page(self) -> None:
        ...

    def is_register_form_usable(self) -> bool:
        ...

    def is_firstname_field_empty(self) -> bool:
        ...

    def is_lastname_field_empty(self) -> bool:
        ...

    def is_email_field_empty(self) -> bool:
        ...

    def is_password_field_empty(self) -> bool:
        ...

    def click_login_link(self) -> None:
        ...

    def is_login_page_loaded(self) -> bool:
        ...

    def navigate_back_in_browser_to_register_page(self) -> None:
        ...

    def open_register_page_again(self) -> None:
        ...
    
    def set_desktop_viewport(self) -> None: ...
    def set_tablet_viewport(self) -> None: ...
    def set_mobile_viewport(self) -> None: ...
    def are_register_primary_elements_visible(self) -> bool: ...

    def register_page_uses_https(self) -> bool: ...
    def enter_malicious_firstname_input(self) -> None: ...
    def enter_malicious_lastname_input(self) -> None: ...
    def enter_malicious_email_input(self) -> None: ...
    def enter_malicious_password_input(self) -> None: ...
    def enter_very_long_firstname(self) -> None: ...
    def enter_very_long_lastname(self) -> None: ...
    def enter_very_long_email(self) -> None: ...
    def enter_very_long_password(self) -> None: ...
    def is_register_page_stable(self) -> bool: ...

    def breadcrumb_contains(self, text: str) -> bool: ...
    def click_side_menu_login_link(self) -> None: ...
    def click_side_menu_register_link(self) -> None: ...
    def click_side_menu_forgotten_password_link(self) -> None: ...
    def is_forgotten_password_page_loaded(self) -> bool: ...
    def click_privacy_policy_link(self) -> None: ...
    def is_privacy_policy_opened(self) -> bool: ...
    def execute_registration_dataset(self, dataset_name: str) -> None:
        ...

    def all_registration_dataset_rows_passed(self) -> bool:
        ...