from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class OpenCartChangePasswordPageState:
    page_loaded: bool
    password_field_visible: bool
    confirm_field_visible: bool
    continue_button_visible: bool
    back_button_visible: bool


class OpenCartChangePasswordPagePort(Protocol):

    def open_change_password_page(self) -> None:
        ...
    def read_change_password_page_state(self) -> OpenCartChangePasswordPageState:
        ...
    def enter_valid_new_password(self) -> None:
        ...
    def enter_same_confirm_password(self) -> None:
        ...
    def enter_different_confirm_password(self) -> None:
        ...
    def submit_change_password_form(self) -> None:
        ...
    def submit_change_password_form_without_passwords(self) -> None:
        ...
    def is_password_changed_successfully(self) -> bool:
        ...
    def is_password_validation_error_displayed(self) -> bool:
        ...
    def is_confirm_password_validation_error_displayed(self) -> bool:
        ...
    def is_password_mismatch_validation_error_displayed(self) -> bool:
        ...
    def is_password_field_masked(self) -> bool:
        ...
    def is_confirm_password_field_masked(self) -> bool:
        ...
    def click_back_button(self) -> None:
        ...
    def is_my_account_page_loaded(self) -> bool:
        ...
    def latest_new_password(self) -> str | None:
        ...
    def breadcrumb_contains(self, text: str) -> bool:
        ...
    def click_side_menu_my_account_link(self) -> None:
        ...
    def click_side_menu_edit_account_link(self) -> None:
        ...
    def click_side_menu_password_link(self) -> None:
        ...
    def click_side_menu_logout_link(self) -> None:
        ...
    def is_edit_account_page_loaded(self) -> bool:
        ...
    def is_logged_out_successfully(self) -> bool:
        ...
    def set_desktop_viewport(self) -> None:
        ...
    def set_tablet_viewport(self) -> None:
        ...
    def set_mobile_viewport(self) -> None:
        ...
    def is_change_password_form_usable(self) -> bool:
        ...
    def are_change_password_primary_elements_visible(self) -> bool:
        ...
    def change_password_page_uses_https(self) -> bool:
        ...
    def enter_malicious_password_input(self) -> None:
        ...
    def enter_malicious_confirm_input(self) -> None:
        ...
    def is_change_password_page_stable(self) -> bool:
        ...
    def is_javascript_alert_displayed(self) -> bool:
        ...
    def clear_authenticated_session(self) -> None:
        ...
    def open_change_password_page_directly(self) -> None:
        ...
    def is_redirected_to_login_page(self) -> bool:
        ...
    def logout_after_password_change(self) -> None:
        ...
    def login_with_newly_changed_password(self) -> None:
        ...
    def login_with_old_password_after_password_change(self) -> None:
        ...
    def is_logged_in_after_password_change(self) -> bool:
        ...
    def is_login_warning_displayed_after_password_change(self) -> bool:
        ...
    def refresh_change_password_page(self) -> None:
        ...
    def is_password_field_empty(self) -> bool:
        ...
    def is_confirm_password_field_empty(self) -> bool:
        ...