from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class OpenCartLoginPageState:
    page_loaded: bool
    returning_customer_section_visible: bool
    email_field_visible: bool
    password_field_visible: bool
    login_button_visible: bool
    forgotten_password_link_visible: bool

@dataclass(frozen=True)
class LoginResultState:
    warning_visible: bool
    warning_text: str | None
    logged_in: bool

class OpenCartLoginPagePort(Protocol):

    def open_login_page(self) -> None:
        ...
    def read_login_page_state(self) -> OpenCartLoginPageState:
        ...
    def navigate_to_forgotten_password_page(self) -> None:
        ...
    def navigate_to_register_account_page(self) -> None:
        ...
    def is_forgotten_password_page_loaded(self) -> bool:
        ...
    def is_register_account_page_loaded(self) -> bool:
        ...
    def enter_email(self, email: str) -> None:
        ...
    def enter_password(self, password: str) -> None:
        ...
    def submit_login(self) -> None:
        ...
    def read_login_result_state(self) -> LoginResultState:
        ...
    def is_password_masked(self) -> bool:
        ...
    def breadcrumb_contains(self, text: str) -> bool:
        ...
    def click_side_menu_register_link(self) -> None:
        ...
    def click_side_menu_forgotten_password_link(self) -> None:
        ...
    def click_side_menu_login_link(self) -> None:
        ...
    def open_my_account_page_directly(self) -> None:
        ...
    def open_edit_account_page_directly(self) -> None:
        ...
    def open_change_password_page_directly(self) -> None:
        ...
    def is_redirected_to_login_page(self) -> bool:
        ...
    def is_my_account_page_loaded(self) -> bool:
        ...
    def logout_from_account_area(self) -> None:
        ...
    def is_logged_out_successfully(self) -> bool:
        ...
    def open_login_page_again(self) -> None:
        ...
    def is_authenticated_login_access_handled(self) -> bool:
        ...
    def set_desktop_viewport(self) -> None:
      ...
    def set_tablet_viewport(self) -> None:
        ...
    def set_mobile_viewport(self) -> None:
        ...
    def is_login_form_usable(self) -> bool:
        ...
    def are_primary_elements_visible(self) -> bool:
        ...
    def login_page_uses_https(self) -> bool:
        ...
    def enter_malicious_email_input(self) -> None:
        ...
    def enter_malicious_password_input(self) -> None:
        ...
    def is_browser_native_validation_displayed(self) -> bool:
        ...
    def is_javascript_alert_displayed(self) -> bool:
        ...
    def submit_invalid_credentials_multiple_times(self) -> None:
        ...
    def is_login_page_stable(self) -> bool:
        ...


